### ISSUE TITLE
when used with emacs, immediate segfault when invoking comment-dwim in empty file

### ISSUE THREAD

**Issue by glyph** [tree-sitter-grammars/tree-sitter-toml#3]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.22.6

### Describe the bug

```
Fatal error 11: Segmentation fault
zsh: abort      emacs -nw a.toml
```

### Steps To Reproduce/Bad Parse Tree

1. compile toml to use with tree-sitter

```elisp
(require 'treesit)
    (let ((treesit-language-source-alist
           `((toml . ("https://github.com/tree-sitter-grammars/tree-sitter-toml"
                      nil nil nil nil)))))
      (treesit-install-language-grammar 'toml))
```

2. `emacs -nw a.toml`
3. hit meta-; to insert a comment

see the segfautl

### Expected Behavior/Parse Tree

I expect it to not segfault

### Repro

See above

**Comment by ObserverOfTime** [comment]
Does that not happen with other parsers?

**Comment by glyph** [comment]
> Does that not happen with other parsers?

Only tried `python-ts-mode`, but no, not with that one.

**Comment by ObserverOfTime** [comment]
Can you get a stack trace or core dump?

**Comment by glyph** [comment]
There's an `ips` file that macOS captured, which appears to contain a stack trace, but the only tree-sitter thing I see on the stack seems to be `Ftreesit_node_type` .  If this is helpful, though, here it is:

[Emacs-2024-06-19-004357.ips.json](https://github.com/user-attachments/files/15911476/Emacs-2024-06-19-004357.ips.json)

**Comment by ObserverOfTime** [comment]
What I can tell from this is that it's trying to access a NULL pointer somewhere.

**Comment by ObserverOfTime** [comment]
I can't reproduce the crash on Arch Linux. It might be a macOS or ARM-specific issue.
I suggest trying a few more parsers and submitting a bug report to emacs if any of them also crash.

**Comment by glyph** [comment]
(Or, none have *this* specific issue).

Is there any diagnostic I can perform locally that will produce a more useful artifact for you?

**Comment by ObserverOfTime** [comment]
Maybe @amaanq can help with that.

**Comment by glyph** [comment]
This stopped happening, but I don't know what I upgraded.  I can no longer reproduce.
