### ISSUE TITLE
Request: Tree-sitter dependency bump.

### ISSUE THREAD

**Issue by kosayoda** [tree-sitter-grammars/tree-sitter-toml#4]
### Did you check the tree-sitter docs?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

Hello! Tree-sitter v0.23.0 is out, which brings a change to the dependecy grammars depend on (from `tree-sitter` to `tree-sitter-language`).

### Describe the solution you'd like

Would it be possible to create a new release with the new dependency version? Thanks!

**Comment by amaanq** [comment]
Just released a new version, sorry about the delay
